name: Manual Deploy

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version to deploy (e.g. v1.0.0)"
        required: true
        default: "v1.0.0"
      environment:
        description: "Deployment environment"
        required: true
        type: choice
        options:
          - production
          - staging
          - testing

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Show deployment info
        run: |
          echo "🚀 Starting deployment..."
          echo "Version: ${{ github.event.inputs.version }}"
          echo "Environment: ${{ github.event.inputs.environment }}"
          echo "Triggered by: ${{ github.actor }}"
